- hosts: cluster
  remote_user: root
  gather_facts: no
  
  tasks:
  - name: try stop firewalld
    service: name=firewalld state=stopped
    ignore_errors: yes

  - name: try stop iptables
    service: name=iptables state=stopped
    ignore_errors: yes

  - name: try disable firewalld
    service: name=firewalld enabled=no
    ignore_errors: yes

  - name: try disable iptables
    service: name=iptables enabled=no
    ignore_errors: yes
