---
- import_playbook: require_check.yaml

# 修改主机名
- import_playbook: hostname.yaml

# 安装控制机依赖
- import_playbook: control.yaml

# 安装系统基本依赖
- import_playbook: system_base.yaml 

# 关闭防火墙
- import_playbook: firewalld.yaml

# 下载二进制文件
- import_playbook: download_bin.yaml

# install docker
- import_playbook: install-docker.yaml

# 创建证书
- import_playbook: cert.yaml

# 安装etcd
- import_playbook: install-etcd-cluster.yaml

# 安装master
- import_playbook: install-kube-apiserver.yaml
- import_playbook: install-kube-controller-manager.yaml
- import_playbook: install-kube-scheduler.yaml

- import_playbook: conf-lb-vip.yaml

# config kube admin
- import_playbook: conf-kube-kubectl.yaml

# config nodes
- import_playbook: install-kube-node.yaml

# install flannel 
- import_playbook: install-flannel-network.yaml

# install dns
- import_playbook: install-kube-dns.yaml

# install dashborad and kong
- import_playbook: deploy-kubernetes-dashboard.yaml
- import_playbook: deploy-kong-api-gateway.yaml
