  - hosts: localhost
    connection: local
    tasks:
      - name: import /kubedns-cm and kubedns-sa
        shell: kubectl apply -f ../template/yml_template/kubedns-cm.yaml ; kubectl create -f  ../template/yml_template/kubedns-sa.yaml
        ignore_errors: true

      - name: build kubedns-controller.yaml
        template:
          src: ../template/yml_template/kubedns-controller.yaml.base
          dest: ../generate/kubedns-controller.yaml
        register: controller

      - name: build kubedns-svc.yaml
        template:
          src: ../template/yml_template/kubedns-svc.yaml.base
          dest: ../generate/kubedns-svc.yaml
        register: kubedns_svc

      # - name: remove lod  kubedns-svc
      #   shell: kubectl delete -f ../generate/kubedns-svc.yaml
      #   when: kubedns_svc.changed == true
      #   ignore_errors: true

      # - name: remove lod  kubedns-controller
      #   shell: kubectl delete -f ../generate/kubedns-controller.yaml
      #   when: controller.changed == true
      #   ignore_errors: true
      
      - name: import kubedns-svc and kubedns-controller
        shell: kubectl apply -f ../generate/kubedns-controller.yaml ;  kubectl apply -f ../generate/kubedns-svc.yaml
        ignore_errors: true
        register: import_dns
        when: kubedns_svc.changed == true or controller.changed == true

      - name: wait kubedns ready
        shell: kubectl get pod -n kube-system | grep kube-dns | grep 3/3 -q
        register: kubedns_status
        until: kubedns_status.rc == 0
        retries: 10
        delay: 5

      - name: scale kubedns replicas
        shell: kubectl --namespace=kube-system scale deployment kube-dns --replicas=3
