---
  - hosts: lb
    tasks:
      - name: get lb host info
        debug: msg='running...'

  - hosts: nodes
    tasks:
      - name: get nodes host info
        debug: msg='running...'

  - hosts: localhost
    connection: local
    vars:
      svc: kube-controller_manager
    tasks:
      - name: check controller_manager csr exists or not
        stat: 
          path: ../generate/controller-manager.csr
        register: controller_manager_csr
    
      - name: check controller_manager pem exists or not
        stat:
          path: ../generate/controller-manager.pem
        register: controller_manager_pem
    
      - name: check controller_manager key exists or not
        stat:
          path: ../generate/controller-manager-key.pem
        register: controller_manager_key
    
      # - name: check controller_manager cert json exists or not
      #   stat:
      #     path: ../generate/controller-manager-csr.json
      #   register: controller_manager_json

      - name: get masters cluster ip
        shell: "echo {% for host in groups['nodes'] %}
                        {{ hostvars[host]['ansible_default_ipv4']['address'] }}
                     {% endfor %}"
        register: NODES_IP
        # when: controller_manager_json.stat.exists == false

      - name: get lb node ip
        shell: "echo {% for host in groups['lb'] %}
                        {{ hostvars[host]['ansible_default_ipv4']['address'] }}
                     {% endfor %}"
        register: LB_IP
        # when: controller_manager_json.stat.exists == false

#      - name: get lb info
#        shell: "echo {% for host in groups['lb_info'] %}
#                        {{ host }}
#                     {% endfor %}"
#        register: LB_INFO
        # when: controller_manager_json.stat.exists == false

      - name: create kube-controller_manager cert json
        shell: cat ../template/json_template/controller-manager-csr.json | ../tools/format_json_template2.py add strip=, {{ NODES_IP.stdout }} {{ LB_IP.stdout }} {{ ha_api_ip }}  > ../generate/controller-manager-csr-origin.json

  
      - name: try apply new controller-manager-csr.json
        copy: src=../generate/controller-manager-csr-origin.json dest=../generate/controller-manager-csr.json
        register: cmc_json


      - name: create controller_manager key and cert
        shell:  cfssl gencert -ca=../generate/ca.pem -ca-key=../generate/ca-key.pem -config=../template/json_template/ca-config.json -profile=sonny ../generate/controller-manager-csr.json | cfssljson -bare ../generate/controller-manager
        when: (controller_manager_csr.stat.exists == false) or
          (controller_manager_pem.stat.exists == false) or
          (controller_manager_key.stat.exists == false) or
          (cmc_json.chagned == true)
