---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.244.3.11:8080"
  restuser: user
  restuserkey: ""
reclaimPolicy: Delete # or "Retain"