apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: glusterfs-storage
  resources:
    requests:
      storage: 10G
        