---
  # ----------------------- start config docker lvm -----
  - name: check device status
    shell: file {{ docker_storage }}

  - name: check devive use status
    stat:
      path: /dev/mapper/docker-thinpool
    register: docker_lvm_status

  - name: create docker lvm
    shell: set -e \
      pvcreate {{ docker_storage }}; \
      vgcreate docker {{ docker_storage }}; \
      lvcreate --wipesignatures y -n thinpool docker -l 95%VG; \
      lvcreate --wipesignatures y -n thinpoolmeta docker -l 1%VG; \
      lvconvert -y \
      --zero n \
      -c 512K \
      --thinpool docker/thinpool \
      --poolmetadata docker/thinpoolmeta ; set +e

    when: docker_lvm_status.stat.exists == false

  - name: set docker lvm profile
    lineinfile:
      path: /etc/lvm/profile/docker-thinpool.profile
      create: yes
      state: present
      mode: 644
      line: "{{ item }}"
    register: profile_status
    with_items:
      - activation {
      - "    thin_pool_autoextend_threshold=80"
      - "    thin_pool_autoextend_percent=20"
      - "    }"
    notify:
      - restart {{ var_docker_engine.stdout | default(["svc"]) }}
  
  - name: apply docker lvm profile
    shell:  lvchange --metadataprofile docker-thinpool docker/thinpool; \
      lvs -o+seg_monitor; \
      set +e \
    when: profile_status.changed == true

  # ----------------------- end config docker lvm -----
    
  - name: config /etc/sysconfig/docker
    copy:
      src: ../template/conf/docker
      dest: /etc/sysconfig/
    notify:
      - restart {{ var_docker_engine.stdout | default(["svc"]) }}

  - name: config docker daemon.json
    copy:
      src: ../template/conf/daemon.json
      dest: /etc/docker
    notify:
      - restart {{ var_docker_engine.stdout | default(["svc"]) }}
      - enable {{ var_docker_engine.stdout | default(["svc"]) }}

  - name: config docker docker-storage      
    lineinfile:
      path: /etc/sysconfig/docker-storage
      create: yes
      state: present
      mode: 644
      line: DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper --storage-opt dm.fs=xfs \
      --storage-opt dm.thinpooldev=/dev/mapper/docker-thinpool --storage-opt dm.use_deferred_removal=true \
      --storage-opt dm.use_deferred_deletion=true"
    notify:
      - restart {{ var_docker_engine.stdout | default(["svc"]) }}
      - enable {{ var_docker_engine.stdout | default(["svc"]) }}