---
  - hosts: localhost
    connection: local
    gather_facts: no
    tasks:
      - name: try import cassandra
        shell: kubectl create -f ../template/yml_template/kong/cassandra.yaml
        ignore_errors: true
        register: cassandra

      - name: cassandra info
        debug:
          msg: cassandra Already exist, reinstall please delete the current
        when: cassandra.rc != 0 

      - name: wait cassandra ready
        shell: kubectl -n default  get pod cassandra-0 | grep 1/1 -q
        register: cassandra_status
        until: cassandra_status.rc == 0
        retries: 30
        delay: 10

      - name: import kong-migration job
        shell: kubectl delete job kong-migration ; kubectl create -f ../template/yml_template/kong/kong_migration_cassandra.yaml
        when: cassandra.rc == 0

      - name: wait kong-migration ready
        shell:  kubectl get job -n default kong-migration | awk 'NR==2 {print $3}'
        register: kong_migration_status
        until: kong_migration_status.stdout.find("1") != -1
        retries: 60
        delay: 10

      - name: build kong
        template:
          src:  ../template/yml_template/kong/kong_cassandra.yaml
          dest: ../generate/

      - name: try import kong
        shell: kubectl -n default  create -f ../generate/kong_cassandra.yaml
        ignore_errors: true

      - name: kong ready
        shell: kubectl -n default get pod | grep kong-rc | awk '{print $2}' | wc -l
        register: kong_status
        until: kong_status.stdout.find("3") != -1
        retries: 30
        delay: 10

      - name: "create k8s-dashborad api , address: https://{{ kong_ip }}:8000/dashboard"
        shell: bash ../tools/create_kong_api.sh {{ kong_ip }}
        ignore_errors: true

      - name: show kong api info
        debug:
          msg: "exec: 'kubectl get svc' get kong api gateway info,  k8s dashborad address: https://{{ kong_ip }}:8000/dashboard"
