---
  - name: debug
    debug:
      msg: "svc = {{ svc }}"
  - name: reload svc
    command: systemctl daemon-reload

  - name: start svc
    service:
      name: "{{ svc }}"
      state: started

  - name: enable svc
    service:
      name: "{{ svc }}"
      enabled: yes

  - name: restart svc
    service:
      name: "{{ svc }}"
      state: restarted

  - name: stop svc
    service:
      name: "{{ svc }}"
      state: stopped
 
  - name: restart apiserver
    service:
      name: kube-apiserver
      state: restarted

  - name: restart haproxy
    service:
      name: haproxy
      state: restarted

  - name: enable haproxy
    service:
      name: haproxy
      enabled: yes
 
  - name: status
    shell: systemctl status {{ svc }}
